% function MaxIntensityFinding (correlation_map)
%
% Description: 
% This function finds the maximum values inside a Correlation
% Map and generate an intensity map with markers plotted on the map to
% locate  the maximums on the correlation map. 
%
% Fields: correlation_map 
%
% Pre-Condition: correlation_map must be a intensity map generated by the
% correlation function 
%
% Post-Condition: an intensity map showing where the maximums are on the
% correlation map. 
%

function Intensity_Map = MaxIntensityFinding (correlation_map)

    % filter all pixel data that are below average
    correlation_map = transpose(correlation_map(find(correlation_map > 0)));
   
    % traverse through first half of matrix to find local maximums 
    Intensity_Map = GenerateIntensityMap(correlation_map);
  
end

% function Intensity_Map_Matrix = GenerateIntensityMap(corr_matrix)
%
% Description: 
% This function generates intensity map for individual correlation matrix
%
% Fields: corr_matrix
%
% Pre-Condition: corr_matrix must be generated through correlation functon 
%
% Post-Condition: an intensity map showing where the maximums are on the
% correlation map. 
%
function Intensity_Map_Matrix = GenerateIntensityMap(corr_matrix)

    
    distance_threshold = 10;  % dummy value, subject to change
    
    size_corr = size(corr_matrix);
    
    for idx = 1 : size_corr(2)
        
        ref_pixel = corr_matrix(idx);
        
        % commence pixel comparison 
        for idx2 = 1:distance_threshold
        
        
        
        
        end

    

    end

end