% function Intensities_Normalization_Fun(correlation_map, testimage)
% 
% Description:
%        
% This function normalizes the correlation map and set map intensities to
% be between 0 and 1
%
% Fields: correlation_map, testimage
%   
% Initial conditions:
% 
% correlation_map must be a data matrix generated by the correlation
% function
%
% testimage is a data matrix representing the image the correlation map has
% analyzed
%   
% Final conditions: None 
%

function [Outlier_array, group_intense_array] =Intensities_Normalization_Fun(correlation_map)
    
    % normalize the correlation map 
    high_value = max(correlation_map(:));
    low_image = 0.34; % default intensity used to normalize the image
      
    correlation_map(correlation_map < low_image) = 0;
    correlation_map = correlation_map ./ high_value;
    
    user_input_low = 0.6;
    user_input_high = 1;
    [Outlier_array, group_intense_array] = Peak_Finding(correlation_map, user_input_low, user_input_high);
end
   